### ISSUE TITLE
Use of unsafe Javascript functions

### ISSUE THREAD

**Issue by jornfranke** [aduth/turbo-combine-reducers#1]
This project uses unsafe Javascript functions, such as the Function operator. For example (there might be more):
https://github.com/aduth/turbo-combine-reducers/blob/master/index.js#L25

This means this package and all the software depending on it is a prime candidate for XSS attacks. See also here: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/script-src#unsafe_eval_expressions (section unsafe-eval-expressions).

See also related project that uses this package:
https://github.com/WordPress/gutenberg/issues/42513

**Comment by aduth** [comment]
Hello. Yes, generally speaking the function constructor can be risky, especially in combination with unsafe user inputs. That risk is mitigated in this project by limiting the scope of inputs, expecting them not to be user-defined, and controlling them to act predictably with spec-guaranteed behavior. I believe that the project is safe to use, but please do send a proof-of-concept to andrew@andrewduthie.com if you are aware of a security vulnerability, and I'd be happy to take a look.

Since the key optimization of the library relies on this implementation, it's not something I would plan to change, since otherwise the project may as well not exist, and someone could opt to use [the default `combineReducers` shipped with Redux](https://redux.js.org/api/combinereducers) instead.

That being said, I do agree with you on two major points:

* This security implication should have been clearly and transparently outlined in the documentation so that other projects can make that risk assessment themselves
* The incompatibility with a CSP should discourage someone from using it if they want to support that use-case (such as in Gutenberg)

I've updated the README text in 6ab352484a3e2276ae1fbf4e546d7515cf09b174 and I'll plan to leave a comment of support in the related Gutenberg issue.
